<?xml version="1.0"?>
<!DOCTYPE animals [
<!ELEMENT animals (animal*)>
<!ELEMENT animal (name, colour, skin, sound)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT skin (#PCDATA)>
<!ELEMENT sound (#PCDATA)>
]>
<animals>
        <animal>
        <name>cow</name>
        <colour>white</colour>
        <skin>leather</skin>
        <sound>moo</sound>
        </animal>
        <animal>
        <name>chicken</name>
        <colour>brown</colour>
        <skin>feathers</skin>
        <sound>cawcaw</sound>
        </animal>
        <animal>
        <name>pig</name>
        <colour>pink</colour>
        <skin>hair</skin>
        <sound>oink</sound>
        </animal>
        <animal>
        <name>horse</name>
        <colour>black</colour>
        <skin>leather</skin>
        <sound>clawking</sound>
        </animal>
</animals>
